[theme]
primaryColor         = "#4A94BB"
backgroundColor      = "#F2F6FA"
secondaryBackgroundColor = "#FFFFFF"
textColor            = "#1A3D5C"
font                 = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
